

public enum EEvent
{
    None = 0,
    Blacksmith = 1,

}

public enum EOption
{
    None = 0,
    Leave = 1,
    Ignore = 2,
    Run = 3,
    Hide = 4,
    Dodge = 5,
    Feint = 6,
    Bluff = 7,
    Intemidate = 8,
    Fight = 9,
    Spar = 10,
    Search = 11,
    Enter = 12,
    Camp = 13,
    Continue = 14,
    Open = 15,
    Close = 16,
    Loot = 17,
    Take = 18,
    Steal = 19,
    Trade = 20,
    Give = 21,
    Offer = 22,
    Donate = 23,
    Shop = 24,
    Buy = 25,
    Sell = 26,
    Forge = 27,
    Play = 28,
    Train = 29,
    Talk = 30,
    Sing = 31,
    Dance = 32,
    Agree = 33,
    Argue = 34,
    Laugh = 35,
    Hug = 36,
    Read = 37,
    Eat = 38,
    Quaff = 39,
    Rock = 40,
    Paper = 41,
    Scissors = 42,
    Right = 43,
    Middle = 44,
    Left = 45,
    Red = 46,
    Green = 47,
    Blue = 48,
    High = 49,
    Low = 50,

}

public enum EOutcome
{
    None = 0,
    GoldGet = 1,
    GoldLose = 2,
    RelicGet = 3,
    RelicLose = 4,
    RelicTrade = 5,
    ItemLose = 6,
    ItemGet = 7,
    EquipmentGet = 8,
    EquipmentLose = 9,
    EquipmentTrade = 10,
    EquipmentUp = 11,
    EquipmentDown = 12,
    RarityUp = 13,
    RarityDown = 14,
    DaggerGet = 15,
    ShieldGet = 16,
    SwordGet = 17,
    AxeGet = 18,
    HammerGet = 19,
    WandGet = 20,
    ScrollGet = 21,
    PotionGet = 22,
    DaggerUp = 23,
    DaggerDown = 24,
    SheildUp = 25,
    SheildDown = 26,
    SwordUp = 27,
    SwordDown = 28,
    AxeUp = 29,
    AxeDown = 30,
    HammerUp = 31,
    HammerDown = 32,
    NatureUp = 33,
    NatureDown = 34,
    FireUp = 35,
    FireDown = 36,
    IceUp = 37,
    IceDown = 38,
    BloodUp = 39,
    BloodDown = 40,
    ShadowUp = 41,
    ShadowDown = 42,
    ArmorUp = 43,
    ArmorDown = 44,
    MagicResistUp = 45,
    MagicResistDown = 46,
    StrengthUp = 47,
    StrengthDown = 48,
    SpellPowerUp = 49,
    SpellPowerDown = 50,
    HealthUp = 51,
    HealthDown = 52,
    CritUp = 53,
    CritDown = 54,
    Buff = 55,
    Debuff = 56,
    Battle = 57,
    ReviveGet = 58,
    ReviveLose = 59,

}